package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"mock-pipefy-api/graph/model"
)

// CreateCard is the resolver for the createCard field.
func (r *mutationResolver) CreateCard(ctx context.Context, input model.CreateCardInput) (*model.CreateCardPayload, error) {
	fmt.Printf("Creating card: pipeId=%d title=%s\n", input.PipeID, input.Title)
	for _, f := range input.FieldsAttributes {
		fmt.Printf("  field: %s = %s\n", f.FieldID, f.FieldValue)
	}

	return &model.CreateCardPayload{
		Card: &model.CreatedCard{
			Title: input.Title,
		},
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
