package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"log/slog"

	"mock-pipefy-api/graph/model"
)

// CreateCard is the resolver for the createCard field.
func (r *mutationResolver) CreateCard(ctx context.Context, input model.CreateCardInput) (*model.CreateCardPayload, error) {
	slog.InfoContext(ctx, "create card received", "pipe_id", input.PipeID, "title", input.Title, "fields_count", len(input.FieldsAttributes))
	for _, f := range input.FieldsAttributes {
		slog.DebugContext(ctx, "create card field", "field_id", f.FieldID, "value", f.FieldValue)
	}

	return &model.CreateCardPayload{
		Card: &model.CreatedCard{
			Title: input.Title,
		},
	}, nil
}

// UpdateFieldsValues is the resolver for the updateFieldsValues field.
func (r *mutationResolver) UpdateFieldsValues(ctx context.Context, input model.UpdateFieldsValuesInput) (*model.UpdateFieldsValuesPayload, error) {
	slog.InfoContext(ctx, "update card fields received", "node_id", input.NodeID, "fields_count", len(input.Values))
	for _, f := range input.Values {
		slog.DebugContext(ctx, "update card field", "field_id", f.FieldID, "value", f.Value)
	}

	return &model.UpdateFieldsValuesPayload{
		Success: true,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
