// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	ID     string       `json:"id"`
	Title  string       `json:"title"`
	PipeID int32        `json:"pipeId"`
	Fields []*CardField `json:"fields"`
}

type CardField struct {
	FieldID    string `json:"fieldId"`
	FieldValue string `json:"fieldValue"`
}

type CreateCardInput struct {
	PipeID           int32                  `json:"pipeId"`
	Title            string                 `json:"title"`
	FieldsAttributes []*FieldAttributeInput `json:"fieldsAttributes"`
}

type CreateCardPayload struct {
	Card *CreatedCard `json:"card"`
}

type CreatedCard struct {
	Title string `json:"title"`
}

type FieldAttributeInput struct {
	FieldID    string `json:"fieldId"`
	FieldValue string `json:"fieldValue"`
}

type Mutation struct {
}

type Query struct {
}
